### PR TITLE
[W5.7][T16-3]Koh Chi Hao

### PR DESCRIPTION
**Pull request by kohchihao**
- Add Sort Command
- Add JUnit Test for UniquePersonList
- Update I/O files for test
- Update UserGuide content to include sort command

### CODE REVIEW

**Comment by monmanuela** [comment]
Looks good to me! Great job implementing the sort command and the testing. 👍

**Comment by jinyingtan** [comment]
PR looks good!

**Review by tanhengyeow — APPROVED** [review]
Good job with the enhancement! It is a clean PR and I observed that you updated the following which is a good practice:
1. User Guide
2. Test cases (both I/O and JUnit tests)

Keep up the good work!

**Comment by tanhengyeow** [comment]
As usual, please close the PR after acknowledging the comments 😄

**Pull request closed without merging**
