### PR TITLE
[W5.7][F10-3]Dong SiJi

### PR DESCRIPTION
**Pull request by dongsiji**
Changed find command to be not case sensitive.

### CODE REVIEW

**Review by liaujianjie — APPROVED** [review]
LGTM 👍

**Comment by ganchinyao** [comment]
Good job in making the find command not case sensitive. This is really a really useful feature in production code.

**Review by dalessr — APPROVED** [review]
@dongsiji Well done for modifying the `find` command 👍

Please close the PR after looking at the comments.

**Comment by dongsiji** [comment]
closed

**Pull request closed without merging**
