### PR TITLE
[W4.11e][F10-4] ANG ZHI KAI

### PR DESCRIPTION
**Pull request by azhikai**
Added the following test case in `AddresBookTest.java` that ensures the `defaultAddressBook` has been properly initialized.

```java
    @Test
    public void addressBook_nonNull_returnsTrue() {
        assertNotNull(defaultAddressBook);
    }
```

### CODE REVIEW

**Comment by azhikai** [comment]
Still WIP. Completing last few LOs.

**Comment by azhikai** [comment]
Ready for review.
Encountered an issue earlier when Travis is building my commit which added `nextSequence` to `Person` class. It failed because the output was mismatched -- nothing I can do on my end other than reversing the commit.

**Comment by damithc** [comment]
@AZhiKai this PR should contain code for `W4.11e` only.

**Comment by azhikai** [comment]
@damithc  Oh my bad, I forgot about that portion and continued working on the rest. I will close this PR and make a new one. 

New PR created at #30

**Pull request closed without merging**
